language: python
python:
  - "2.7"
  - "2.6"
before_install: sudo apt-get install libxml2-dev libxslt-dev
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests src/breadability/tests
